name: Deploy Kenku FM (Windows Only)

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Kenku FM
    runs-on: windows-latest

    env:
      NODE_VERSION: 22
      PYTHON_VERSION: 3.9.13
      CASTLABS_ACCOUNT_NAME: ${{ secrets.CASTLABS_ACCOUNT_NAME }}
      CASTLABS_ACCOUNT_PASSWORD: ${{ secrets.CASTLABS_ACCOUNT_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Latest Yarn
        uses: threeal/setup-yarn-action@v2.0.0
        with:
          version: latest

      - name: Build package
        if: github.event_name != 'release'
        run: yarn run make

      - name: Publish release assets to GitHub
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish
